# Generated by porcelain: do not edit by hand
`__porcelain__` <- function() {
  list(
    "GET /version" = function(state, validate) {
      porcelain::porcelain_endpoint$new(
        "GET",
        "/version",
        version,
        returning = porcelain::porcelain_returning_json("string"),
        validate = validate)
    })
}
